paths:
  # require mithril library
  'mithril': 'mithril/mithril'
  # require jquery library
  'jquery': 'jquery/dist/jquery'<% if (includeLodash) { %>
  # require lodash
  'lodash': 'lodash/dist/lodash'<% } %>
  # bootstrap library
  'bootstrap': 'bootstrap-sprockets'
shim:
  'mithril':
    exports: 'm'<% if (includeLodash) { %>
  'lodash':
    exports: '_'<% } %>
  'bootstrap': ['jquery']
